# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [5]:
# Create our features
X = df.copy()
X.drop(["home_ownership", "verification_status", "application_type", "issue_d", "loan_status", "pymnt_plan", "initial_list_status", "next_pymnt_d", "hardship_flag", "debt_settlement_flag"], axis=1, inplace=True)
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,0.0,3.0,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,0.0,6.0,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,0.0,4.0,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,0.0,1.0,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,0.0,1.0,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0

In [6]:
# Create our target
y = df["loan_status"].ravel()
y[:5]

array(['low_risk', 'low_risk', 'low_risk', 'low_risk', 'low_risk'],
      dtype=object)

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,6.881700e+04,6.881700e+04,68817.000000,6.881700e+04
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.052138,2.219423,95.057627,30.626217,0.125972,0.0,2.100332e+05,6.133843e+04,29734.128558,5.572240e+04
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.390633,1.897432,8.326426,33.631463,0.336732,0.0,1.928088e+05,5.738798e+04,26795.394232,5.095845e+04
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,20.000000,0.000000,0.000000,0.0,3.600000e+03,2.350000e+02,100.000000,1.270000e+02
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.000000,93.000000,0.000000,0.000000,0.0,6.697700e+04,2.650300e+04,11600.000000,2.288000e+04
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,2.000000,100.000000,20.000000,0.000000,0.0,1.467100e+05,4.535700e+04,22100.000000,4.200000e+04
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,3.000000,100.000000,50.000000,0.000000,0.0,3.036400e+05,7.657000e+04,39300.000000,7.249900e+04
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,18.000000,19.000000,100.000000,100.000000,4.000000,0.0,3.292782e+06,1.295455e+06,509400.000000,1.426964e+06

In [8]:
# Check the balance of our target values
# YOUR CODE HERE

In [9]:
# Split the X and y into X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [10]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [11]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
X_scaler = scaler.fit(X_train)

In [12]:
# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [13]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators=1000, random_state=1)
brf.fit(X_train_scaled, y_train)

BalancedRandomForestClassifier(n_estimators=1000, random_state=1)

In [14]:
# Calculated the balanced accuracy score
y_pred = brf.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.7155867656456946

In [15]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   60,    41],
       [ 2786, 14318]], dtype=int64)

In [16]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.02      0.59      0.84      0.04      0.71      0.49       101
   low_risk       1.00      0.84      0.59      0.91      0.71      0.51     17104

avg / total       0.99      0.84      0.60      0.91      0.71      0.51     17205

In [17]:
# List the features sorted in descending order by feature importance
importances = brf.feature_importances_

sorted(zip(brf.feature_importances_, X.columns), reverse=True)

[(0.07267016482273941, 'total_rec_prncp'),
 (0.0620218417096884, 'total_rec_int'),
 (0.06135682735275659, 'last_pymnt_amnt'),
 (0.055918562094267044, 'total_pymnt'),
 (0.055565405745193884, 'total_pymnt_inv'),
 (0.03545975710552551, 'int_rate'),
 (0.01989293954233566, 'mths_since_recent_inq'),
 (0.0193330331302457, 'dti'),
 (0.017014398026206044, 'installment'),
 (0.016967561073087566, 'annual_inc'),
 (0.016500230493699693, 'out_prncp_inv'),
 (0.016349981452691092, 'max_bal_bc'),
 (0.01612131086287136, 'avg_cur_bal'),
 (0.01599130433665954, 'revol_bal'),
 (0.015976538118397086, 'tot_hi_cred_lim'),
 (0.015887073002665134, 'out_prncp'),
 (0.015650515881079363, 'mo_sin_old_rev_tl_op'),
 (0.015381061042762994, 'bc_util'),
 (0.015380553315633698, 'total_bc_limit'),
 (0.015023018582536837, 'mths_since_rcnt_il'),
 (0.014936571761064502, 'bc_open_to_buy'),
 (0.01491995638826405, 'total_bal_il'),
 (0.01481700781354611, 'tot_cur_bal'),
 (0.014773168358444366, 'mo_sin_old_il_acct'),
 (0.014654144556662592, 'il_util'),
 (0.014598324227997126, 'all_util'),
 (0.014064406003809753, 'total_rev_hi_lim'),
 (0.013976140157829551, 'total_bal_ex_mort'),
 (0.01343734468123707, 'total_il_high_credit_limit'),
 (0.012724294661781025, 'loan_amnt'),
 (0.011775782554087314, 'mths_since_recent_bc'),
 (0.011555152067000701, 'total_acc'),
 (0.011530338090446209, 'inq_last_12m'),
 (0.011049215479364567, 'num_rev_accts'),
 (0.010964920480462985, 'pct_tl_nvr_dlq'),
 (0.010616571526234976, 'num_op_rev_tl'),
 (0.010583642230546772, 'num_il_tl'),
 (0.010366964307152933, 'mo_sin_rcnt_tl'),
 (0.010016981881846122, 'mo_sin_rcnt_rev_tl_op'),
 (0.009974682287949404, 'open_acc'),
 (0.009641567958100986, 'num_bc_tl'),
 (0.009608247023449161, 'num_sats'),
 (0.009583447589380035, 'acc_open_past_24mths'),
 (0.00894266099053309, 'num_rev_tl_bal_gt_0'),
 (0.008788365030998356, 'num_actv_rev_tl'),
 (0.008782915344407224, 'open_il_24m'),
 (0.008439239917455064, 'num_tl_op_past_12m'),
 (0.008336008734114006, 'inq_fi'),
 (0.008126882320385519, 'open_acc_6m'),
 (0.008087470264828738, 'total_rec_late_fee'),
 (0.008036741973703689, 'percent_bc_gt_75'),
 (0.00796056063658511, 'total_cu_tl'),
 (0.007959507628215097, 'num_actv_bc_tl'),
 (0.007669540438248364, 'num_bc_sats'),
 (0.006905338446429054, 'open_act_il'),
 (0.006622903832755803, 'open_rv_24m'),
 (0.006318063369798684, 'mort_acc'),
 (0.005761592895201128, 'open_il_12m'),
 (0.0055505264837954925, 'inq_last_6mths'),
 (0.005248654777414196, 'open_rv_12m'),
 (0.0041952188841746455, 'tot_coll_amt'),
 (0.004129581809470968, 'delinq_2yrs'),
 (0.0038883196013097324, 'num_accts_ever_120_pd'),
 (0.001950759034698784, 'pub_rec'),
 (0.0017851769325609975, 'pub_rec_bankruptcies'),
 (0.001119397263687152, 'num_tl_90g_dpd_24m'),
 (0.0005314220949795116, 'collections_12_mths_ex_med'),
 (0.00022508193065896411, 'chargeoff_within_12_mths'),
 (7.1195858898242e-06, 'delinq_amnt'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [18]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=1000, random_state=1)
eec.fit(X_train_scaled, y_train)

EasyEnsembleClassifier(n_estimators=1000, random_state=1)

In [19]:
# Calculated the balanced accuracy score
y_pred2 = eec.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred2)

0.716183869907103

In [20]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred2)

array([[   67,    34],
       [ 3951, 13153]], dtype=int64)

In [21]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred2))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.02      0.66      0.77      0.03      0.71      0.50       101
   low_risk       1.00      0.77      0.66      0.87      0.71      0.52     17104

avg / total       0.99      0.77      0.66      0.86      0.71      0.52     17205

### Final Questions

1. Which model had the best balanced accuracy score?

    The model that had the better balanced accuracy score is the Easy Ensemble Classifier with 0.71618, compared to 0.71558 of the Balanced Random Forest Classifier.

2. Which model had the best recall score?

    The model that had the better recall score is the  Balanced Random Forest Classifier with 0.84, compared to 0.77 of the Easy Ensemble Classifier.

3. Which model had the best geometric mean score?

    The two models had the same geometric mean score of 0.71.

4. What are the top three features?

    The top three features are the Total Received Principal, Total Received Interest and Last Payment Amount.